### ISSUE TITLE
correção de erro

### ISSUE THREAD

**Issue by shaylcm** [misaelrezende/Exercicios-do-Livro-Linguagem-C-Completa-e-Descomplicada#6]
A verificação não estava funcionando nos primeiros números ,por causa do for(j = 0; j < i-1 ; j++) na parte de j<i-1, portanto tirei para ver o que acontecia , a verificação foi feita do inicio ao fim.

**Comment by misaelrezende** [comment]
Obrigado pela contribuição @shaylcm. 
Issue relacionada ao exercício 13 do capítulo 6 (6.7.1).
